### ISSUE TITLE
NotoNaskhArabic v2.018 ?

### ISSUE THREAD

**Issue by x1sc0** [notofonts/arabic#238]
Today I found there is a new tag of NotoNaskhArabic [<https://github.com/notofonts/arabic/tags>](https://github.com/notofonts/arabic/tags) which is v2.018, However, I'm confused because that tag already existed, See https://cgit.freedesktop.org/libreoffice/core/commit/?id=36de604067b5b76de90a09ab8a1760623c9a4afe or another commit I found https://cgit.freebsd.org/ports/commit/?id=ec1399734712502ecfad2d2816328c5aa2f8cc43
Should it be v2.019 instead ?

**Comment by simoncozens** [comment]
I'm not sure what is going on with that tag. I definitely tagged and released 2.018 on November 22nd and there has been no source changes since then. Maybe I did something stupid with git while rebasing and ended it up moving the tag? It's obviously not ideal, but there are no differences between the "old" 2.018 and the "new" 2.018, so I'm not sure that there's anything to be done to fix this.

**Comment by x1sc0** [comment]
thanks for the clarification!!
