### ISSUE TITLE
The Nastaliq Urdu font should not be chosen for Arabic or Persian text

### ISSUE THREAD

**Issue by tonijarjour** [notofonts/arabic#240]
This does not happen when both Dejavu and Noto Fonts are installed. Urdu pages are displayed with the Urdu font, while Arabic and Persian are displayed with a Dejavu font.
I may be mistaken, but to me this implies the problem is with the Noto Fonts package.

I can't read this:
![image](https://github.com/notofonts/arabic/assets/39845673/36c862a9-e67f-43ad-a86c-7c5c7c6f3ed5)

**Comment by tonijarjour** [comment]
This happens on both Chromium and Firefox. OS is Arch Linux.
This image is WITHOUT Dejavu installed.
![out](https://github.com/notofonts/arabic/assets/39845673/bd7b9fbd-fc7f-4c79-9e52-5cede0639f91)
This is with Dejavu installed.
![out2](https://github.com/notofonts/arabic/assets/39845673/57f26015-ea30-4048-84ad-65ab3cdf537d)

The only thing I want is for it to work properly with Noto on its own. I can fix it for my personal computer, but for everyone else it is incorrect.

**Comment by avidseeker** [comment]
Related discussion: https://gitlab.freedesktop.org/fontconfig/fontconfig/-/issues/173

**Comment by simoncozens** [comment]
Yep, further confirmation that this is due to the way that fontconfig is choosing fonts. When you have two fonts - Noto Naskh Arabic and Noto Nastaliq Urdu - which both support the Arabic codepoints, fontconfig doesn't currently have any good heuristic for "knowing" which one is appropriate for Urdu and which for Arabic.

There is a solution to this long term - the `dlng` and `slng` entries in the `meta` table, which allow the font to provide that information. But fontconfig doesn't currently read that table, and we don't currently provide it. We should start doing so. It won't fix your problem, but it means that when fontconfig learns how to read the meta table, things can start working.

**Comment by simoncozens** [comment]
I've now added the meta table to Noto Nastaliq Arabic, and hopefully at some point in the future, software will know to prefer it for Urdu, Kashmiri, Kyrgyz, Uyghur, Balochi and Crimean Tatar, but not for Arabic, Farsi, etc.
